package org.fbi.trc.tqc.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.trc.tqc.repository.model.TqcQuotaMchtHis;
import org.fbi.trc.tqc.repository.model.TqcQuotaMchtHisExample;

public interface TqcQuotaMchtHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_MCHT_HIS
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int countByExample(TqcQuotaMchtHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_MCHT_HIS
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int deleteByExample(TqcQuotaMchtHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_MCHT_HIS
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_MCHT_HIS
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int insert(TqcQuotaMchtHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_MCHT_HIS
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int insertSelective(TqcQuotaMchtHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_MCHT_HIS
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    List<TqcQuotaMchtHis> selectByExample(TqcQuotaMchtHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_MCHT_HIS
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    TqcQuotaMchtHis selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_MCHT_HIS
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int updateByExampleSelective(@Param("record") TqcQuotaMchtHis record, @Param("example") TqcQuotaMchtHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_MCHT_HIS
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int updateByExample(@Param("record") TqcQuotaMchtHis record, @Param("example") TqcQuotaMchtHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_MCHT_HIS
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int updateByPrimaryKeySelective(TqcQuotaMchtHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_MCHT_HIS
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int updateByPrimaryKey(TqcQuotaMchtHis record);
}