package org.fbi.trc.tqc.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.trc.tqc.repository.model.TqcQuotaAcct;
import org.fbi.trc.tqc.repository.model.TqcQuotaAcctExample;
import org.fbi.trc.tqc.repository.model.TqcQuotaAcctKey;

public interface TqcQuotaAcctMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int countByExample(TqcQuotaAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int deleteByExample(TqcQuotaAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int deleteByPrimaryKey(TqcQuotaAcctKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int insert(TqcQuotaAcct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int insertSelective(TqcQuotaAcct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    List<TqcQuotaAcct> selectByExample(TqcQuotaAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    TqcQuotaAcct selectByPrimaryKey(TqcQuotaAcctKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int updateByExampleSelective(@Param("record") TqcQuotaAcct record, @Param("example") TqcQuotaAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int updateByExample(@Param("record") TqcQuotaAcct record, @Param("example") TqcQuotaAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int updateByPrimaryKeySelective(TqcQuotaAcct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_QUOTA_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int updateByPrimaryKey(TqcQuotaAcct record);
}