package org.fbi.trc.tqc.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.trc.tqc.repository.model.TqcRuleAcct;
import org.fbi.trc.tqc.repository.model.TqcRuleAcctExample;
import org.fbi.trc.tqc.repository.model.TqcRuleAcctKey;

public interface TqcRuleAcctMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_ACCT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    int countByExample(TqcRuleAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_ACCT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    int deleteByExample(TqcRuleAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_ACCT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    int deleteByPrimaryKey(TqcRuleAcctKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_ACCT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    int insert(TqcRuleAcct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_ACCT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    int insertSelective(TqcRuleAcct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_ACCT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    List<TqcRuleAcct> selectByExample(TqcRuleAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_ACCT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    TqcRuleAcct selectByPrimaryKey(TqcRuleAcctKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_ACCT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    int updateByExampleSelective(@Param("record") TqcRuleAcct record, @Param("example") TqcRuleAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_ACCT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    int updateByExample(@Param("record") TqcRuleAcct record, @Param("example") TqcRuleAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_ACCT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    int updateByPrimaryKeySelective(TqcRuleAcct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_RULE_ACCT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    int updateByPrimaryKey(TqcRuleAcct record);
}