package org.fbi.trc.tqc.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.trc.tqc.repository.model.TqcTxnAcct;
import org.fbi.trc.tqc.repository.model.TqcTxnAcctExample;

public interface TqcTxnAcctMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int countByExample(TqcTxnAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int deleteByExample(TqcTxnAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int insert(TqcTxnAcct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int insertSelective(TqcTxnAcct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    List<TqcTxnAcct> selectByExample(TqcTxnAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    TqcTxnAcct selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int updateByExampleSelective(@Param("record") TqcTxnAcct record, @Param("example") TqcTxnAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int updateByExample(@Param("record") TqcTxnAcct record, @Param("example") TqcTxnAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int updateByPrimaryKeySelective(TqcTxnAcct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    int updateByPrimaryKey(TqcTxnAcct record);
}