package org.fbi.trc.tqc.repository.model;

import java.math.BigDecimal;

public class TqcQuotaMcht extends TqcQuotaMchtKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_QUOTA_MCHT.ACCT_NO
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String acctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_QUOTA_MCHT.VCH_SN
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String vchSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_QUOTA_MCHT.TXN_DATE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_QUOTA_MCHT.TXN_DAY_AMT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private BigDecimal txnDayAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_QUOTA_MCHT.TXN_MONTH_AMT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private BigDecimal txnMonthAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_QUOTA_MCHT.TXN_DAY_CNT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private Integer txnDayCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_QUOTA_MCHT.TXN_MONTH_CNT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private Integer txnMonthCnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_QUOTA_MCHT.REMARK
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_QUOTA_MCHT.ACCT_NO
     *
     * @return the value of TRC.TQC_QUOTA_MCHT.ACCT_NO
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_QUOTA_MCHT.ACCT_NO
     *
     * @param acctNo the value for TRC.TQC_QUOTA_MCHT.ACCT_NO
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setAcctNo(String acctNo) {
        this.acctNo = acctNo == null ? null : acctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_QUOTA_MCHT.VCH_SN
     *
     * @return the value of TRC.TQC_QUOTA_MCHT.VCH_SN
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getVchSn() {
        return vchSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_QUOTA_MCHT.VCH_SN
     *
     * @param vchSn the value for TRC.TQC_QUOTA_MCHT.VCH_SN
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setVchSn(String vchSn) {
        this.vchSn = vchSn == null ? null : vchSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_QUOTA_MCHT.TXN_DATE
     *
     * @return the value of TRC.TQC_QUOTA_MCHT.TXN_DATE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_QUOTA_MCHT.TXN_DATE
     *
     * @param txnDate the value for TRC.TQC_QUOTA_MCHT.TXN_DATE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_QUOTA_MCHT.TXN_DAY_AMT
     *
     * @return the value of TRC.TQC_QUOTA_MCHT.TXN_DAY_AMT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public BigDecimal getTxnDayAmt() {
        return txnDayAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_QUOTA_MCHT.TXN_DAY_AMT
     *
     * @param txnDayAmt the value for TRC.TQC_QUOTA_MCHT.TXN_DAY_AMT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setTxnDayAmt(BigDecimal txnDayAmt) {
        this.txnDayAmt = txnDayAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_QUOTA_MCHT.TXN_MONTH_AMT
     *
     * @return the value of TRC.TQC_QUOTA_MCHT.TXN_MONTH_AMT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public BigDecimal getTxnMonthAmt() {
        return txnMonthAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_QUOTA_MCHT.TXN_MONTH_AMT
     *
     * @param txnMonthAmt the value for TRC.TQC_QUOTA_MCHT.TXN_MONTH_AMT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setTxnMonthAmt(BigDecimal txnMonthAmt) {
        this.txnMonthAmt = txnMonthAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_QUOTA_MCHT.TXN_DAY_CNT
     *
     * @return the value of TRC.TQC_QUOTA_MCHT.TXN_DAY_CNT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public Integer getTxnDayCnt() {
        return txnDayCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_QUOTA_MCHT.TXN_DAY_CNT
     *
     * @param txnDayCnt the value for TRC.TQC_QUOTA_MCHT.TXN_DAY_CNT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setTxnDayCnt(Integer txnDayCnt) {
        this.txnDayCnt = txnDayCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_QUOTA_MCHT.TXN_MONTH_CNT
     *
     * @return the value of TRC.TQC_QUOTA_MCHT.TXN_MONTH_CNT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public Integer getTxnMonthCnt() {
        return txnMonthCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_QUOTA_MCHT.TXN_MONTH_CNT
     *
     * @param txnMonthCnt the value for TRC.TQC_QUOTA_MCHT.TXN_MONTH_CNT
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setTxnMonthCnt(Integer txnMonthCnt) {
        this.txnMonthCnt = txnMonthCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_QUOTA_MCHT.REMARK
     *
     * @return the value of TRC.TQC_QUOTA_MCHT.REMARK
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_QUOTA_MCHT.REMARK
     *
     * @param remark the value for TRC.TQC_QUOTA_MCHT.REMARK
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}