package org.fbi.trc.tqc.repository.model;

import java.math.BigDecimal;

public class TqcRuleAcct extends TqcRuleAcctKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.MCHT_NAME
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String mchtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.AREA_RULE_FLAG
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String areaRuleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.AREA_CODE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.SINGLE_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private BigDecimal singleLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.DAY_AMT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private BigDecimal dayAmtLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.MONTH_AMT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private BigDecimal monthAmtLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.DAY_CNT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private Integer dayCntLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.MONTH_CNT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private Integer monthCntLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.RECVER
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private Integer recver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.REMARK
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.OPER_ID
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_ACCT.OPER_DATE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String operDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.MCHT_NAME
     *
     * @return the value of TRC.TQC_RULE_ACCT.MCHT_NAME
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getMchtName() {
        return mchtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.MCHT_NAME
     *
     * @param mchtName the value for TRC.TQC_RULE_ACCT.MCHT_NAME
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setMchtName(String mchtName) {
        this.mchtName = mchtName == null ? null : mchtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.AREA_RULE_FLAG
     *
     * @return the value of TRC.TQC_RULE_ACCT.AREA_RULE_FLAG
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getAreaRuleFlag() {
        return areaRuleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.AREA_RULE_FLAG
     *
     * @param areaRuleFlag the value for TRC.TQC_RULE_ACCT.AREA_RULE_FLAG
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setAreaRuleFlag(String areaRuleFlag) {
        this.areaRuleFlag = areaRuleFlag == null ? null : areaRuleFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.AREA_CODE
     *
     * @return the value of TRC.TQC_RULE_ACCT.AREA_CODE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.AREA_CODE
     *
     * @param areaCode the value for TRC.TQC_RULE_ACCT.AREA_CODE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.SINGLE_LIM
     *
     * @return the value of TRC.TQC_RULE_ACCT.SINGLE_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public BigDecimal getSingleLim() {
        return singleLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.SINGLE_LIM
     *
     * @param singleLim the value for TRC.TQC_RULE_ACCT.SINGLE_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setSingleLim(BigDecimal singleLim) {
        this.singleLim = singleLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.DAY_AMT_LIM
     *
     * @return the value of TRC.TQC_RULE_ACCT.DAY_AMT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public BigDecimal getDayAmtLim() {
        return dayAmtLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.DAY_AMT_LIM
     *
     * @param dayAmtLim the value for TRC.TQC_RULE_ACCT.DAY_AMT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setDayAmtLim(BigDecimal dayAmtLim) {
        this.dayAmtLim = dayAmtLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.MONTH_AMT_LIM
     *
     * @return the value of TRC.TQC_RULE_ACCT.MONTH_AMT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public BigDecimal getMonthAmtLim() {
        return monthAmtLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.MONTH_AMT_LIM
     *
     * @param monthAmtLim the value for TRC.TQC_RULE_ACCT.MONTH_AMT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setMonthAmtLim(BigDecimal monthAmtLim) {
        this.monthAmtLim = monthAmtLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.DAY_CNT_LIM
     *
     * @return the value of TRC.TQC_RULE_ACCT.DAY_CNT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public Integer getDayCntLim() {
        return dayCntLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.DAY_CNT_LIM
     *
     * @param dayCntLim the value for TRC.TQC_RULE_ACCT.DAY_CNT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setDayCntLim(Integer dayCntLim) {
        this.dayCntLim = dayCntLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.MONTH_CNT_LIM
     *
     * @return the value of TRC.TQC_RULE_ACCT.MONTH_CNT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public Integer getMonthCntLim() {
        return monthCntLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.MONTH_CNT_LIM
     *
     * @param monthCntLim the value for TRC.TQC_RULE_ACCT.MONTH_CNT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setMonthCntLim(Integer monthCntLim) {
        this.monthCntLim = monthCntLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.RECVER
     *
     * @return the value of TRC.TQC_RULE_ACCT.RECVER
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public Integer getRecver() {
        return recver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.RECVER
     *
     * @param recver the value for TRC.TQC_RULE_ACCT.RECVER
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setRecver(Integer recver) {
        this.recver = recver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.REMARK
     *
     * @return the value of TRC.TQC_RULE_ACCT.REMARK
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.REMARK
     *
     * @param remark the value for TRC.TQC_RULE_ACCT.REMARK
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.OPER_ID
     *
     * @return the value of TRC.TQC_RULE_ACCT.OPER_ID
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.OPER_ID
     *
     * @param operId the value for TRC.TQC_RULE_ACCT.OPER_ID
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_ACCT.OPER_DATE
     *
     * @return the value of TRC.TQC_RULE_ACCT.OPER_DATE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_ACCT.OPER_DATE
     *
     * @param operDate the value for TRC.TQC_RULE_ACCT.OPER_DATE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }
}