package org.fbi.trc.tqc.repository.model;

import java.math.BigDecimal;

public class TqcRuleArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_AREA.AREA_CODE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_AREA.AREA_NAME
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_AREA.SINGLE_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private BigDecimal singleLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_AREA.DAY_AMT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private BigDecimal dayAmtLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_AREA.MONTH_AMT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private BigDecimal monthAmtLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_AREA.DAY_CNT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private Integer dayCntLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_AREA.MONTH_CNT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private Integer monthCntLim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_AREA.RECVER
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private Integer recver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_AREA.REMARK
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_AREA.OPER_ID
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRC.TQC_RULE_AREA.OPER_DATE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    private String operDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_AREA.AREA_CODE
     *
     * @return the value of TRC.TQC_RULE_AREA.AREA_CODE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_AREA.AREA_CODE
     *
     * @param areaCode the value for TRC.TQC_RULE_AREA.AREA_CODE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_AREA.AREA_NAME
     *
     * @return the value of TRC.TQC_RULE_AREA.AREA_NAME
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_AREA.AREA_NAME
     *
     * @param areaName the value for TRC.TQC_RULE_AREA.AREA_NAME
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_AREA.SINGLE_LIM
     *
     * @return the value of TRC.TQC_RULE_AREA.SINGLE_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public BigDecimal getSingleLim() {
        return singleLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_AREA.SINGLE_LIM
     *
     * @param singleLim the value for TRC.TQC_RULE_AREA.SINGLE_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setSingleLim(BigDecimal singleLim) {
        this.singleLim = singleLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_AREA.DAY_AMT_LIM
     *
     * @return the value of TRC.TQC_RULE_AREA.DAY_AMT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public BigDecimal getDayAmtLim() {
        return dayAmtLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_AREA.DAY_AMT_LIM
     *
     * @param dayAmtLim the value for TRC.TQC_RULE_AREA.DAY_AMT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setDayAmtLim(BigDecimal dayAmtLim) {
        this.dayAmtLim = dayAmtLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_AREA.MONTH_AMT_LIM
     *
     * @return the value of TRC.TQC_RULE_AREA.MONTH_AMT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public BigDecimal getMonthAmtLim() {
        return monthAmtLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_AREA.MONTH_AMT_LIM
     *
     * @param monthAmtLim the value for TRC.TQC_RULE_AREA.MONTH_AMT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setMonthAmtLim(BigDecimal monthAmtLim) {
        this.monthAmtLim = monthAmtLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_AREA.DAY_CNT_LIM
     *
     * @return the value of TRC.TQC_RULE_AREA.DAY_CNT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public Integer getDayCntLim() {
        return dayCntLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_AREA.DAY_CNT_LIM
     *
     * @param dayCntLim the value for TRC.TQC_RULE_AREA.DAY_CNT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setDayCntLim(Integer dayCntLim) {
        this.dayCntLim = dayCntLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_AREA.MONTH_CNT_LIM
     *
     * @return the value of TRC.TQC_RULE_AREA.MONTH_CNT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public Integer getMonthCntLim() {
        return monthCntLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_AREA.MONTH_CNT_LIM
     *
     * @param monthCntLim the value for TRC.TQC_RULE_AREA.MONTH_CNT_LIM
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setMonthCntLim(Integer monthCntLim) {
        this.monthCntLim = monthCntLim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_AREA.RECVER
     *
     * @return the value of TRC.TQC_RULE_AREA.RECVER
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public Integer getRecver() {
        return recver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_AREA.RECVER
     *
     * @param recver the value for TRC.TQC_RULE_AREA.RECVER
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setRecver(Integer recver) {
        this.recver = recver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_AREA.REMARK
     *
     * @return the value of TRC.TQC_RULE_AREA.REMARK
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_AREA.REMARK
     *
     * @param remark the value for TRC.TQC_RULE_AREA.REMARK
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_AREA.OPER_ID
     *
     * @return the value of TRC.TQC_RULE_AREA.OPER_ID
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_AREA.OPER_ID
     *
     * @param operId the value for TRC.TQC_RULE_AREA.OPER_ID
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRC.TQC_RULE_AREA.OPER_DATE
     *
     * @return the value of TRC.TQC_RULE_AREA.OPER_DATE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRC.TQC_RULE_AREA.OPER_DATE
     *
     * @param operDate the value for TRC.TQC_RULE_AREA.OPER_DATE
     *
     * @mbggenerated Tue Oct 21 10:59:00 CST 2014
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }
}