package org.fbi.trc.tqc.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TqcTxnAcctExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    public TqcTxnAcctExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNull() {
            addCriterion("TXN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNotNull() {
            addCriterion("TXN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnDateEqualTo(String value) {
            addCriterion("TXN_DATE =", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotEqualTo(String value) {
            addCriterion("TXN_DATE <>", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThan(String value) {
            addCriterion("TXN_DATE >", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_DATE >=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThan(String value) {
            addCriterion("TXN_DATE <", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThanOrEqualTo(String value) {
            addCriterion("TXN_DATE <=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLike(String value) {
            addCriterion("TXN_DATE like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotLike(String value) {
            addCriterion("TXN_DATE not like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateIn(List<String> values) {
            addCriterion("TXN_DATE in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotIn(List<String> values) {
            addCriterion("TXN_DATE not in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateBetween(String value1, String value2) {
            addCriterion("TXN_DATE between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotBetween(String value1, String value2) {
            addCriterion("TXN_DATE not between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoIsNull() {
            addCriterion("TXN_SEQNO is null");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoIsNotNull() {
            addCriterion("TXN_SEQNO is not null");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoEqualTo(String value) {
            addCriterion("TXN_SEQNO =", value, "txnSeqno");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoNotEqualTo(String value) {
            addCriterion("TXN_SEQNO <>", value, "txnSeqno");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoGreaterThan(String value) {
            addCriterion("TXN_SEQNO >", value, "txnSeqno");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_SEQNO >=", value, "txnSeqno");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoLessThan(String value) {
            addCriterion("TXN_SEQNO <", value, "txnSeqno");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoLessThanOrEqualTo(String value) {
            addCriterion("TXN_SEQNO <=", value, "txnSeqno");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoLike(String value) {
            addCriterion("TXN_SEQNO like", value, "txnSeqno");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoNotLike(String value) {
            addCriterion("TXN_SEQNO not like", value, "txnSeqno");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoIn(List<String> values) {
            addCriterion("TXN_SEQNO in", values, "txnSeqno");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoNotIn(List<String> values) {
            addCriterion("TXN_SEQNO not in", values, "txnSeqno");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoBetween(String value1, String value2) {
            addCriterion("TXN_SEQNO between", value1, value2, "txnSeqno");
            return (Criteria) this;
        }

        public Criteria andTxnSeqnoNotBetween(String value1, String value2) {
            addCriterion("TXN_SEQNO not between", value1, value2, "txnSeqno");
            return (Criteria) this;
        }

        public Criteria andMchtCodeIsNull() {
            addCriterion("MCHT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMchtCodeIsNotNull() {
            addCriterion("MCHT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMchtCodeEqualTo(String value) {
            addCriterion("MCHT_CODE =", value, "mchtCode");
            return (Criteria) this;
        }

        public Criteria andMchtCodeNotEqualTo(String value) {
            addCriterion("MCHT_CODE <>", value, "mchtCode");
            return (Criteria) this;
        }

        public Criteria andMchtCodeGreaterThan(String value) {
            addCriterion("MCHT_CODE >", value, "mchtCode");
            return (Criteria) this;
        }

        public Criteria andMchtCodeGreaterThanOrEqualTo(String value) {
            addCriterion("MCHT_CODE >=", value, "mchtCode");
            return (Criteria) this;
        }

        public Criteria andMchtCodeLessThan(String value) {
            addCriterion("MCHT_CODE <", value, "mchtCode");
            return (Criteria) this;
        }

        public Criteria andMchtCodeLessThanOrEqualTo(String value) {
            addCriterion("MCHT_CODE <=", value, "mchtCode");
            return (Criteria) this;
        }

        public Criteria andMchtCodeLike(String value) {
            addCriterion("MCHT_CODE like", value, "mchtCode");
            return (Criteria) this;
        }

        public Criteria andMchtCodeNotLike(String value) {
            addCriterion("MCHT_CODE not like", value, "mchtCode");
            return (Criteria) this;
        }

        public Criteria andMchtCodeIn(List<String> values) {
            addCriterion("MCHT_CODE in", values, "mchtCode");
            return (Criteria) this;
        }

        public Criteria andMchtCodeNotIn(List<String> values) {
            addCriterion("MCHT_CODE not in", values, "mchtCode");
            return (Criteria) this;
        }

        public Criteria andMchtCodeBetween(String value1, String value2) {
            addCriterion("MCHT_CODE between", value1, value2, "mchtCode");
            return (Criteria) this;
        }

        public Criteria andMchtCodeNotBetween(String value1, String value2) {
            addCriterion("MCHT_CODE not between", value1, value2, "mchtCode");
            return (Criteria) this;
        }

        public Criteria andPrjCodeIsNull() {
            addCriterion("PRJ_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPrjCodeIsNotNull() {
            addCriterion("PRJ_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPrjCodeEqualTo(String value) {
            addCriterion("PRJ_CODE =", value, "prjCode");
            return (Criteria) this;
        }

        public Criteria andPrjCodeNotEqualTo(String value) {
            addCriterion("PRJ_CODE <>", value, "prjCode");
            return (Criteria) this;
        }

        public Criteria andPrjCodeGreaterThan(String value) {
            addCriterion("PRJ_CODE >", value, "prjCode");
            return (Criteria) this;
        }

        public Criteria andPrjCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PRJ_CODE >=", value, "prjCode");
            return (Criteria) this;
        }

        public Criteria andPrjCodeLessThan(String value) {
            addCriterion("PRJ_CODE <", value, "prjCode");
            return (Criteria) this;
        }

        public Criteria andPrjCodeLessThanOrEqualTo(String value) {
            addCriterion("PRJ_CODE <=", value, "prjCode");
            return (Criteria) this;
        }

        public Criteria andPrjCodeLike(String value) {
            addCriterion("PRJ_CODE like", value, "prjCode");
            return (Criteria) this;
        }

        public Criteria andPrjCodeNotLike(String value) {
            addCriterion("PRJ_CODE not like", value, "prjCode");
            return (Criteria) this;
        }

        public Criteria andPrjCodeIn(List<String> values) {
            addCriterion("PRJ_CODE in", values, "prjCode");
            return (Criteria) this;
        }

        public Criteria andPrjCodeNotIn(List<String> values) {
            addCriterion("PRJ_CODE not in", values, "prjCode");
            return (Criteria) this;
        }

        public Criteria andPrjCodeBetween(String value1, String value2) {
            addCriterion("PRJ_CODE between", value1, value2, "prjCode");
            return (Criteria) this;
        }

        public Criteria andPrjCodeNotBetween(String value1, String value2) {
            addCriterion("PRJ_CODE not between", value1, value2, "prjCode");
            return (Criteria) this;
        }

        public Criteria andAcctNoIsNull() {
            addCriterion("ACCT_NO is null");
            return (Criteria) this;
        }

        public Criteria andAcctNoIsNotNull() {
            addCriterion("ACCT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAcctNoEqualTo(String value) {
            addCriterion("ACCT_NO =", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoNotEqualTo(String value) {
            addCriterion("ACCT_NO <>", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoGreaterThan(String value) {
            addCriterion("ACCT_NO >", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoGreaterThanOrEqualTo(String value) {
            addCriterion("ACCT_NO >=", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoLessThan(String value) {
            addCriterion("ACCT_NO <", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoLessThanOrEqualTo(String value) {
            addCriterion("ACCT_NO <=", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoLike(String value) {
            addCriterion("ACCT_NO like", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoNotLike(String value) {
            addCriterion("ACCT_NO not like", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoIn(List<String> values) {
            addCriterion("ACCT_NO in", values, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoNotIn(List<String> values) {
            addCriterion("ACCT_NO not in", values, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoBetween(String value1, String value2) {
            addCriterion("ACCT_NO between", value1, value2, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoNotBetween(String value1, String value2) {
            addCriterion("ACCT_NO not between", value1, value2, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNameIsNull() {
            addCriterion("ACCT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAcctNameIsNotNull() {
            addCriterion("ACCT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAcctNameEqualTo(String value) {
            addCriterion("ACCT_NAME =", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameNotEqualTo(String value) {
            addCriterion("ACCT_NAME <>", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameGreaterThan(String value) {
            addCriterion("ACCT_NAME >", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameGreaterThanOrEqualTo(String value) {
            addCriterion("ACCT_NAME >=", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameLessThan(String value) {
            addCriterion("ACCT_NAME <", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameLessThanOrEqualTo(String value) {
            addCriterion("ACCT_NAME <=", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameLike(String value) {
            addCriterion("ACCT_NAME like", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameNotLike(String value) {
            addCriterion("ACCT_NAME not like", value, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameIn(List<String> values) {
            addCriterion("ACCT_NAME in", values, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameNotIn(List<String> values) {
            addCriterion("ACCT_NAME not in", values, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameBetween(String value1, String value2) {
            addCriterion("ACCT_NAME between", value1, value2, "acctName");
            return (Criteria) this;
        }

        public Criteria andAcctNameNotBetween(String value1, String value2) {
            addCriterion("ACCT_NAME not between", value1, value2, "acctName");
            return (Criteria) this;
        }

        public Criteria andVchSnIsNull() {
            addCriterion("VCH_SN is null");
            return (Criteria) this;
        }

        public Criteria andVchSnIsNotNull() {
            addCriterion("VCH_SN is not null");
            return (Criteria) this;
        }

        public Criteria andVchSnEqualTo(String value) {
            addCriterion("VCH_SN =", value, "vchSn");
            return (Criteria) this;
        }

        public Criteria andVchSnNotEqualTo(String value) {
            addCriterion("VCH_SN <>", value, "vchSn");
            return (Criteria) this;
        }

        public Criteria andVchSnGreaterThan(String value) {
            addCriterion("VCH_SN >", value, "vchSn");
            return (Criteria) this;
        }

        public Criteria andVchSnGreaterThanOrEqualTo(String value) {
            addCriterion("VCH_SN >=", value, "vchSn");
            return (Criteria) this;
        }

        public Criteria andVchSnLessThan(String value) {
            addCriterion("VCH_SN <", value, "vchSn");
            return (Criteria) this;
        }

        public Criteria andVchSnLessThanOrEqualTo(String value) {
            addCriterion("VCH_SN <=", value, "vchSn");
            return (Criteria) this;
        }

        public Criteria andVchSnLike(String value) {
            addCriterion("VCH_SN like", value, "vchSn");
            return (Criteria) this;
        }

        public Criteria andVchSnNotLike(String value) {
            addCriterion("VCH_SN not like", value, "vchSn");
            return (Criteria) this;
        }

        public Criteria andVchSnIn(List<String> values) {
            addCriterion("VCH_SN in", values, "vchSn");
            return (Criteria) this;
        }

        public Criteria andVchSnNotIn(List<String> values) {
            addCriterion("VCH_SN not in", values, "vchSn");
            return (Criteria) this;
        }

        public Criteria andVchSnBetween(String value1, String value2) {
            addCriterion("VCH_SN between", value1, value2, "vchSn");
            return (Criteria) this;
        }

        public Criteria andVchSnNotBetween(String value1, String value2) {
            addCriterion("VCH_SN not between", value1, value2, "vchSn");
            return (Criteria) this;
        }

        public Criteria andVchSnPreIsNull() {
            addCriterion("VCH_SN_PRE is null");
            return (Criteria) this;
        }

        public Criteria andVchSnPreIsNotNull() {
            addCriterion("VCH_SN_PRE is not null");
            return (Criteria) this;
        }

        public Criteria andVchSnPreEqualTo(String value) {
            addCriterion("VCH_SN_PRE =", value, "vchSnPre");
            return (Criteria) this;
        }

        public Criteria andVchSnPreNotEqualTo(String value) {
            addCriterion("VCH_SN_PRE <>", value, "vchSnPre");
            return (Criteria) this;
        }

        public Criteria andVchSnPreGreaterThan(String value) {
            addCriterion("VCH_SN_PRE >", value, "vchSnPre");
            return (Criteria) this;
        }

        public Criteria andVchSnPreGreaterThanOrEqualTo(String value) {
            addCriterion("VCH_SN_PRE >=", value, "vchSnPre");
            return (Criteria) this;
        }

        public Criteria andVchSnPreLessThan(String value) {
            addCriterion("VCH_SN_PRE <", value, "vchSnPre");
            return (Criteria) this;
        }

        public Criteria andVchSnPreLessThanOrEqualTo(String value) {
            addCriterion("VCH_SN_PRE <=", value, "vchSnPre");
            return (Criteria) this;
        }

        public Criteria andVchSnPreLike(String value) {
            addCriterion("VCH_SN_PRE like", value, "vchSnPre");
            return (Criteria) this;
        }

        public Criteria andVchSnPreNotLike(String value) {
            addCriterion("VCH_SN_PRE not like", value, "vchSnPre");
            return (Criteria) this;
        }

        public Criteria andVchSnPreIn(List<String> values) {
            addCriterion("VCH_SN_PRE in", values, "vchSnPre");
            return (Criteria) this;
        }

        public Criteria andVchSnPreNotIn(List<String> values) {
            addCriterion("VCH_SN_PRE not in", values, "vchSnPre");
            return (Criteria) this;
        }

        public Criteria andVchSnPreBetween(String value1, String value2) {
            addCriterion("VCH_SN_PRE between", value1, value2, "vchSnPre");
            return (Criteria) this;
        }

        public Criteria andVchSnPreNotBetween(String value1, String value2) {
            addCriterion("VCH_SN_PRE not between", value1, value2, "vchSnPre");
            return (Criteria) this;
        }

        public Criteria andTxnAmtIsNull() {
            addCriterion("TXN_AMT is null");
            return (Criteria) this;
        }

        public Criteria andTxnAmtIsNotNull() {
            addCriterion("TXN_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andTxnAmtEqualTo(BigDecimal value) {
            addCriterion("TXN_AMT =", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotEqualTo(BigDecimal value) {
            addCriterion("TXN_AMT <>", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtGreaterThan(BigDecimal value) {
            addCriterion("TXN_AMT >", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TXN_AMT >=", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtLessThan(BigDecimal value) {
            addCriterion("TXN_AMT <", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TXN_AMT <=", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtIn(List<BigDecimal> values) {
            addCriterion("TXN_AMT in", values, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotIn(List<BigDecimal> values) {
            addCriterion("TXN_AMT not in", values, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TXN_AMT between", value1, value2, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TXN_AMT not between", value1, value2, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andChkStatusIsNull() {
            addCriterion("CHK_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andChkStatusIsNotNull() {
            addCriterion("CHK_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andChkStatusEqualTo(String value) {
            addCriterion("CHK_STATUS =", value, "chkStatus");
            return (Criteria) this;
        }

        public Criteria andChkStatusNotEqualTo(String value) {
            addCriterion("CHK_STATUS <>", value, "chkStatus");
            return (Criteria) this;
        }

        public Criteria andChkStatusGreaterThan(String value) {
            addCriterion("CHK_STATUS >", value, "chkStatus");
            return (Criteria) this;
        }

        public Criteria andChkStatusGreaterThanOrEqualTo(String value) {
            addCriterion("CHK_STATUS >=", value, "chkStatus");
            return (Criteria) this;
        }

        public Criteria andChkStatusLessThan(String value) {
            addCriterion("CHK_STATUS <", value, "chkStatus");
            return (Criteria) this;
        }

        public Criteria andChkStatusLessThanOrEqualTo(String value) {
            addCriterion("CHK_STATUS <=", value, "chkStatus");
            return (Criteria) this;
        }

        public Criteria andChkStatusLike(String value) {
            addCriterion("CHK_STATUS like", value, "chkStatus");
            return (Criteria) this;
        }

        public Criteria andChkStatusNotLike(String value) {
            addCriterion("CHK_STATUS not like", value, "chkStatus");
            return (Criteria) this;
        }

        public Criteria andChkStatusIn(List<String> values) {
            addCriterion("CHK_STATUS in", values, "chkStatus");
            return (Criteria) this;
        }

        public Criteria andChkStatusNotIn(List<String> values) {
            addCriterion("CHK_STATUS not in", values, "chkStatus");
            return (Criteria) this;
        }

        public Criteria andChkStatusBetween(String value1, String value2) {
            addCriterion("CHK_STATUS between", value1, value2, "chkStatus");
            return (Criteria) this;
        }

        public Criteria andChkStatusNotBetween(String value1, String value2) {
            addCriterion("CHK_STATUS not between", value1, value2, "chkStatus");
            return (Criteria) this;
        }

        public Criteria andChkTimeIsNull() {
            addCriterion("CHK_TIME is null");
            return (Criteria) this;
        }

        public Criteria andChkTimeIsNotNull() {
            addCriterion("CHK_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andChkTimeEqualTo(String value) {
            addCriterion("CHK_TIME =", value, "chkTime");
            return (Criteria) this;
        }

        public Criteria andChkTimeNotEqualTo(String value) {
            addCriterion("CHK_TIME <>", value, "chkTime");
            return (Criteria) this;
        }

        public Criteria andChkTimeGreaterThan(String value) {
            addCriterion("CHK_TIME >", value, "chkTime");
            return (Criteria) this;
        }

        public Criteria andChkTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CHK_TIME >=", value, "chkTime");
            return (Criteria) this;
        }

        public Criteria andChkTimeLessThan(String value) {
            addCriterion("CHK_TIME <", value, "chkTime");
            return (Criteria) this;
        }

        public Criteria andChkTimeLessThanOrEqualTo(String value) {
            addCriterion("CHK_TIME <=", value, "chkTime");
            return (Criteria) this;
        }

        public Criteria andChkTimeLike(String value) {
            addCriterion("CHK_TIME like", value, "chkTime");
            return (Criteria) this;
        }

        public Criteria andChkTimeNotLike(String value) {
            addCriterion("CHK_TIME not like", value, "chkTime");
            return (Criteria) this;
        }

        public Criteria andChkTimeIn(List<String> values) {
            addCriterion("CHK_TIME in", values, "chkTime");
            return (Criteria) this;
        }

        public Criteria andChkTimeNotIn(List<String> values) {
            addCriterion("CHK_TIME not in", values, "chkTime");
            return (Criteria) this;
        }

        public Criteria andChkTimeBetween(String value1, String value2) {
            addCriterion("CHK_TIME between", value1, value2, "chkTime");
            return (Criteria) this;
        }

        public Criteria andChkTimeNotBetween(String value1, String value2) {
            addCriterion("CHK_TIME not between", value1, value2, "chkTime");
            return (Criteria) this;
        }

        public Criteria andBookFlagIsNull() {
            addCriterion("BOOK_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andBookFlagIsNotNull() {
            addCriterion("BOOK_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andBookFlagEqualTo(String value) {
            addCriterion("BOOK_FLAG =", value, "bookFlag");
            return (Criteria) this;
        }

        public Criteria andBookFlagNotEqualTo(String value) {
            addCriterion("BOOK_FLAG <>", value, "bookFlag");
            return (Criteria) this;
        }

        public Criteria andBookFlagGreaterThan(String value) {
            addCriterion("BOOK_FLAG >", value, "bookFlag");
            return (Criteria) this;
        }

        public Criteria andBookFlagGreaterThanOrEqualTo(String value) {
            addCriterion("BOOK_FLAG >=", value, "bookFlag");
            return (Criteria) this;
        }

        public Criteria andBookFlagLessThan(String value) {
            addCriterion("BOOK_FLAG <", value, "bookFlag");
            return (Criteria) this;
        }

        public Criteria andBookFlagLessThanOrEqualTo(String value) {
            addCriterion("BOOK_FLAG <=", value, "bookFlag");
            return (Criteria) this;
        }

        public Criteria andBookFlagLike(String value) {
            addCriterion("BOOK_FLAG like", value, "bookFlag");
            return (Criteria) this;
        }

        public Criteria andBookFlagNotLike(String value) {
            addCriterion("BOOK_FLAG not like", value, "bookFlag");
            return (Criteria) this;
        }

        public Criteria andBookFlagIn(List<String> values) {
            addCriterion("BOOK_FLAG in", values, "bookFlag");
            return (Criteria) this;
        }

        public Criteria andBookFlagNotIn(List<String> values) {
            addCriterion("BOOK_FLAG not in", values, "bookFlag");
            return (Criteria) this;
        }

        public Criteria andBookFlagBetween(String value1, String value2) {
            addCriterion("BOOK_FLAG between", value1, value2, "bookFlag");
            return (Criteria) this;
        }

        public Criteria andBookFlagNotBetween(String value1, String value2) {
            addCriterion("BOOK_FLAG not between", value1, value2, "bookFlag");
            return (Criteria) this;
        }

        public Criteria andBookTimeIsNull() {
            addCriterion("BOOK_TIME is null");
            return (Criteria) this;
        }

        public Criteria andBookTimeIsNotNull() {
            addCriterion("BOOK_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andBookTimeEqualTo(String value) {
            addCriterion("BOOK_TIME =", value, "bookTime");
            return (Criteria) this;
        }

        public Criteria andBookTimeNotEqualTo(String value) {
            addCriterion("BOOK_TIME <>", value, "bookTime");
            return (Criteria) this;
        }

        public Criteria andBookTimeGreaterThan(String value) {
            addCriterion("BOOK_TIME >", value, "bookTime");
            return (Criteria) this;
        }

        public Criteria andBookTimeGreaterThanOrEqualTo(String value) {
            addCriterion("BOOK_TIME >=", value, "bookTime");
            return (Criteria) this;
        }

        public Criteria andBookTimeLessThan(String value) {
            addCriterion("BOOK_TIME <", value, "bookTime");
            return (Criteria) this;
        }

        public Criteria andBookTimeLessThanOrEqualTo(String value) {
            addCriterion("BOOK_TIME <=", value, "bookTime");
            return (Criteria) this;
        }

        public Criteria andBookTimeLike(String value) {
            addCriterion("BOOK_TIME like", value, "bookTime");
            return (Criteria) this;
        }

        public Criteria andBookTimeNotLike(String value) {
            addCriterion("BOOK_TIME not like", value, "bookTime");
            return (Criteria) this;
        }

        public Criteria andBookTimeIn(List<String> values) {
            addCriterion("BOOK_TIME in", values, "bookTime");
            return (Criteria) this;
        }

        public Criteria andBookTimeNotIn(List<String> values) {
            addCriterion("BOOK_TIME not in", values, "bookTime");
            return (Criteria) this;
        }

        public Criteria andBookTimeBetween(String value1, String value2) {
            addCriterion("BOOK_TIME between", value1, value2, "bookTime");
            return (Criteria) this;
        }

        public Criteria andBookTimeNotBetween(String value1, String value2) {
            addCriterion("BOOK_TIME not between", value1, value2, "bookTime");
            return (Criteria) this;
        }

        public Criteria andTxnDayAmtPreIsNull() {
            addCriterion("TXN_DAY_AMT_PRE is null");
            return (Criteria) this;
        }

        public Criteria andTxnDayAmtPreIsNotNull() {
            addCriterion("TXN_DAY_AMT_PRE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnDayAmtPreEqualTo(BigDecimal value) {
            addCriterion("TXN_DAY_AMT_PRE =", value, "txnDayAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnDayAmtPreNotEqualTo(BigDecimal value) {
            addCriterion("TXN_DAY_AMT_PRE <>", value, "txnDayAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnDayAmtPreGreaterThan(BigDecimal value) {
            addCriterion("TXN_DAY_AMT_PRE >", value, "txnDayAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnDayAmtPreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TXN_DAY_AMT_PRE >=", value, "txnDayAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnDayAmtPreLessThan(BigDecimal value) {
            addCriterion("TXN_DAY_AMT_PRE <", value, "txnDayAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnDayAmtPreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TXN_DAY_AMT_PRE <=", value, "txnDayAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnDayAmtPreIn(List<BigDecimal> values) {
            addCriterion("TXN_DAY_AMT_PRE in", values, "txnDayAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnDayAmtPreNotIn(List<BigDecimal> values) {
            addCriterion("TXN_DAY_AMT_PRE not in", values, "txnDayAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnDayAmtPreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TXN_DAY_AMT_PRE between", value1, value2, "txnDayAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnDayAmtPreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TXN_DAY_AMT_PRE not between", value1, value2, "txnDayAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnMonthAmtPreIsNull() {
            addCriterion("TXN_MONTH_AMT_PRE is null");
            return (Criteria) this;
        }

        public Criteria andTxnMonthAmtPreIsNotNull() {
            addCriterion("TXN_MONTH_AMT_PRE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnMonthAmtPreEqualTo(BigDecimal value) {
            addCriterion("TXN_MONTH_AMT_PRE =", value, "txnMonthAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnMonthAmtPreNotEqualTo(BigDecimal value) {
            addCriterion("TXN_MONTH_AMT_PRE <>", value, "txnMonthAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnMonthAmtPreGreaterThan(BigDecimal value) {
            addCriterion("TXN_MONTH_AMT_PRE >", value, "txnMonthAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnMonthAmtPreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TXN_MONTH_AMT_PRE >=", value, "txnMonthAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnMonthAmtPreLessThan(BigDecimal value) {
            addCriterion("TXN_MONTH_AMT_PRE <", value, "txnMonthAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnMonthAmtPreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TXN_MONTH_AMT_PRE <=", value, "txnMonthAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnMonthAmtPreIn(List<BigDecimal> values) {
            addCriterion("TXN_MONTH_AMT_PRE in", values, "txnMonthAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnMonthAmtPreNotIn(List<BigDecimal> values) {
            addCriterion("TXN_MONTH_AMT_PRE not in", values, "txnMonthAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnMonthAmtPreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TXN_MONTH_AMT_PRE between", value1, value2, "txnMonthAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnMonthAmtPreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TXN_MONTH_AMT_PRE not between", value1, value2, "txnMonthAmtPre");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeIsNull() {
            addCriterion("TXN_REJ_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeIsNotNull() {
            addCriterion("TXN_REJ_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeEqualTo(String value) {
            addCriterion("TXN_REJ_CODE =", value, "txnRejCode");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeNotEqualTo(String value) {
            addCriterion("TXN_REJ_CODE <>", value, "txnRejCode");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeGreaterThan(String value) {
            addCriterion("TXN_REJ_CODE >", value, "txnRejCode");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_REJ_CODE >=", value, "txnRejCode");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeLessThan(String value) {
            addCriterion("TXN_REJ_CODE <", value, "txnRejCode");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeLessThanOrEqualTo(String value) {
            addCriterion("TXN_REJ_CODE <=", value, "txnRejCode");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeLike(String value) {
            addCriterion("TXN_REJ_CODE like", value, "txnRejCode");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeNotLike(String value) {
            addCriterion("TXN_REJ_CODE not like", value, "txnRejCode");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeIn(List<String> values) {
            addCriterion("TXN_REJ_CODE in", values, "txnRejCode");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeNotIn(List<String> values) {
            addCriterion("TXN_REJ_CODE not in", values, "txnRejCode");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeBetween(String value1, String value2) {
            addCriterion("TXN_REJ_CODE between", value1, value2, "txnRejCode");
            return (Criteria) this;
        }

        public Criteria andTxnRejCodeNotBetween(String value1, String value2) {
            addCriterion("TXN_REJ_CODE not between", value1, value2, "txnRejCode");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonIsNull() {
            addCriterion("TXN_REJ_REASON is null");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonIsNotNull() {
            addCriterion("TXN_REJ_REASON is not null");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonEqualTo(String value) {
            addCriterion("TXN_REJ_REASON =", value, "txnRejReason");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonNotEqualTo(String value) {
            addCriterion("TXN_REJ_REASON <>", value, "txnRejReason");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonGreaterThan(String value) {
            addCriterion("TXN_REJ_REASON >", value, "txnRejReason");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_REJ_REASON >=", value, "txnRejReason");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonLessThan(String value) {
            addCriterion("TXN_REJ_REASON <", value, "txnRejReason");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonLessThanOrEqualTo(String value) {
            addCriterion("TXN_REJ_REASON <=", value, "txnRejReason");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonLike(String value) {
            addCriterion("TXN_REJ_REASON like", value, "txnRejReason");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonNotLike(String value) {
            addCriterion("TXN_REJ_REASON not like", value, "txnRejReason");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonIn(List<String> values) {
            addCriterion("TXN_REJ_REASON in", values, "txnRejReason");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonNotIn(List<String> values) {
            addCriterion("TXN_REJ_REASON not in", values, "txnRejReason");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonBetween(String value1, String value2) {
            addCriterion("TXN_REJ_REASON between", value1, value2, "txnRejReason");
            return (Criteria) this;
        }

        public Criteria andTxnRejReasonNotBetween(String value1, String value2) {
            addCriterion("TXN_REJ_REASON not between", value1, value2, "txnRejReason");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 22 11:35:56 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TRC.TQC_TXN_ACCT
     *
     * @mbggenerated Wed Oct 22 11:35:56 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}